language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
notifications:
  email: false
  irc: "chat.freenode.net#bzlist"
install:
  - npm install
  - npm --prefix functions install
script:
  - npm run lint
  - npm run build:ssr
  - npm --prefix functions run build